### ISSUE TITLE
Wallet lock is "reversible" by hitting back

### ISSUE THREAD

**Issue by willgarrett64** [edge/wallet#156]
I put "reversible" between quotation marks because the lock state itself isn't actually reversed, but just UI with the locked modal is reversed. See steps and video below

Repro steps:
- Lock wallet 
- Hit the back button in the browser (or on your mouse)
- User can now navigate freely the UI
- Hit refresh 
- Wallet re-locks (this shows that the locked state does in fact persist)

https://user-images.githubusercontent.com/74154911/151346373-a17314d7-63a1-4050-8c23-d27c5c61e12a.mp4

Acceptance criteria:
Hitting back (or any other method) should not unlock the UI. Only entering the password should unlock it.

**Comment by annybs** [comment]
This is resolved in the merged commit above. I have made minor tweaks but the effect is the same. Attempting to access any part of the wallet while it's locked prevents rendering, even when using browser back navigation.

There is a quirk where e.g. navigating back to `/overview` does not result in the history being modified to redirect back to `/` - the unlock modal is correctly displayed and works fine, but you remain on the `/overview` URL. This is non-breaking and the benefit conferred by any fix is miniscule, so I'm just acknowledging that it's a known quirk.
